config/routes.rb
Rails.application.routes.draw do
  root to: 'documents#index'

  resources :users, only: [:new, :create]
  resources :documents, only: [:index, :show, :new, :create]
  resource :session
end

app/models/document.rb
class Document < ActiveRecord::Base
  validates :owner_id, :name, :loan_amount, :interest_rate, :downpayment, presence: true

  has_attached_file :pdf,
                    :url => ':s3_domain_url',
                    :path => '/:class/:attachment/:id_partition/:style/:filename'

  validates_attachment_content_type :pdf, :content_type => ['application/pdf'], :if => :pdf_attached?

  def pdf_attached?
    self.pdf.file?
  end

  belongs_to(
    :owner,
    class_name: 'User',
    foreign_key: 'owner_id',
    primary_key: 'id'
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password
  after_initialize :ensure_session_token

  has_many(
    :documents,
    class_name: 'Document',
    foreign_key: :owner_id,
    primary_key: :id
  )

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_token!
  end

  def sign_out
    current_user.try(:reset_token!)
    session[:session_token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :require_signed_in!

  def index
    @documents = current_user.documents
  end

  def create
    @document = Document.new(document_params)
    @document.owner_id = current_user.id

    pdf = DocumentPdf.new(@document)
    attachment = pdf.render
    file = StringIO.new(attachment)
    file.class.class_eval { attr_accessor :original_filename, :content_type }
    file.original_filename = "document_#{@document.name}.pdf"
    file.content_type = "application/pdf"
    @document.pdf = file

    if @document.save
      redirect_to documents_url
    else
      flash.now[:errors] = @documents.errors.full_messages
    end
  end

  # You can unncomment this code if you would like to generate a welcome email locally.
  # Then go to http://localhost:3000/documents/1.pdf an an email will be generated in a new tab
  # def show
  #   @document = Document.find(params[:id])
  #
  #   DocumentMailer.document_email(current_user, @document).deliver
  #
  #   respond_to do |format|
  #     format.html
  #     format.pdf do
  #       pdf = DocumentPdf.new(@document)
  #       send_data pdf.render, filename: "document_#{@document.id}.pdf",
  #                             type: "application/pdf",
  #                             disposition: "inline"
  #     end
  #   end
  # end

  private

  def document_params
    params.require(:document).permit(:name, :loan_amount, :interest_rate, :downpayment)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by_credentials(
    params[:user][:email],
    params[:user][:password]
    )

    if user
      sign_in(user)
      redirect_to documents_url
    else
      flash.now[:errors] = ["Invalid email or password"]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to documents_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/index.html.erb
<div class="loan-info">
    <h2>Your Past Loan Quotes:</h2>

    <table class="table table-hover table-bordered table-striped">
      <tr class="heading">
        <td>name</td>
        <td>Loan Amount</td>
        <td>Interest Rate</td>
        <td>Down Payment</td>
        <td>View PDF</td>
      </tr>
  <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td>$<%=document.loan_amount %></td>
        <td><%= document.interest_rate %>%</td>
        <td>$<%=document.downpayment %></td>
        <td><a href='<%=document.pdf.url %>'>View a pdf version</a></td>
      </tr>
  <% end %>
    </table>

  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Get a New Quote</button>

  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="exampleModalLabel">Enter Your Loan Info</h4>
        </div>
        <div class="modal-body">
          <form class="" action="<%= documents_url%>" method="post">
            <input
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">

            <div class="form-group">
              <label class="control-label">Loan Name:</label>
              <input type="text" name="document[name]" class="form-control">
            </div>
            <div class="form-group">
              <label class="control-label">Loan Amount:</label>
              <input type="number" name="document[loan_amount]" class="form-control">
            </div>
            <div class="form-group">
              <label class="control-label">Interest Rate:</label>
              <input type="number" name="document[interest_rate]" class="form-control">
            </div>
            <div class="form-group">
              <label class="control-label">Down Payment Amount:</label>
              <input type="number" name="document[downpayment]" class="form-control">
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Get Quote</button>
            </div>
          </form>
        </div>
    </div>
  </div>
</div>

</div>

app/views/layouts/_errors.html.erb
<!-- <%= flash[:errors].join("<br>").html_safe if flash[:errors] %> -->

<% if flash[:errors] %>
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <%= flash[:errors].join("<br>").html_safe %>
</div>
<% end %>

app/views/layouts/_nav.html.erb
<nav>
    <div class="container">
      <span>QuickLoans</span>


    <div class="login">
      <% if signed_in? %>

      <%= current_user.email %>
      <%= link_to "Sign out", session_url, method: :delete %>
      <% else %>
      <%= link_to "Sign In", new_session_url %>
      <%= link_to "Sign Up", new_user_url %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoanApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: "layouts/nav" %>
  <%= render "layouts/errors" %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class="login-form">
<form class="" action="<%= users_url%>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
    <h2>Sign Up</h2>
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" name="user[email]" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" name="user[password]" class="form-control" id="exampleInputPassword1" placeholder="Password">
      </div>

      <button type="submit" class="btn btn-default">Sign Up</button>
</form>

<div class="sign-up">
  <%= link_to "Click here to Sign In", new_session_url %>
<div>
</div>